{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-react-test/19.0.0-2025.2.8+build.9/kotlin-react-test-19.0.0-2025.2.8+build.9.module",
    "group": "net.cyberflame",
    "module": "kotlin-react-test",
    "version": "19.0.0-2025.2.8+build.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.9.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.9.klib",
          "size": 526,
          "sha512": "ea0e336b51d8bececb7f1d0073a9052ae87feee4a30c375d807bf6b582b3ef19e54e208f9270501d750448db502670ef23a150f95166f20c9226636a13dc5ada",
          "sha256": "ad2c446a1b0604dc207f65d264795560d3dea66f6a22bd332be724e68ec7aefa",
          "sha1": "47cd02bdf796f3f9fc4620f85ce93ea775c5a81e",
          "md5": "8c213f1f019517ca231a0ccbb1cca1fd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.9.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.9.klib",
          "size": 526,
          "sha512": "ea0e336b51d8bececb7f1d0073a9052ae87feee4a30c375d807bf6b582b3ef19e54e208f9270501d750448db502670ef23a150f95166f20c9226636a13dc5ada",
          "sha256": "ad2c446a1b0604dc207f65d264795560d3dea66f6a22bd332be724e68ec7aefa",
          "sha1": "47cd02bdf796f3f9fc4620f85ce93ea775c5a81e",
          "md5": "8c213f1f019517ca231a0ccbb1cca1fd"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.9-sources.jar",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.9-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
