{
  "formatVersion": "1.1",
  "component": {
    "group": "net.turtton",
    "module": "weaver",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "weaver-0.1.0.jar",
          "url": "weaver-0.1.0.jar",
          "size": 16308,
          "sha512": "14f701adf0aaa9b04e3a6f398022502edf8e32f0a468185584466d8679b005878ee8223ae4c21551a642b89fa11418028b0d27b93c2a444ec6e9d760d6875057",
          "sha256": "8bfad454cfe2abb18c6acce3c7ba7d32dc234d67f713fb5614e2eeb1070aeaa4",
          "sha1": "6f3d0b364b56127ce0af009b7f8fd7b43e66eac9",
          "md5": "86df9b9603ddc4bde15315f21feab8d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.7.1+kotlin.1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "weaver-0.1.0.jar",
          "url": "weaver-0.1.0.jar",
          "size": 16308,
          "sha512": "14f701adf0aaa9b04e3a6f398022502edf8e32f0a468185584466d8679b005878ee8223ae4c21551a642b89fa11418028b0d27b93c2a444ec6e9d760d6875057",
          "sha256": "8bfad454cfe2abb18c6acce3c7ba7d32dc234d67f713fb5614e2eeb1070aeaa4",
          "sha1": "6f3d0b364b56127ce0af009b7f8fd7b43e66eac9",
          "md5": "86df9b9603ddc4bde15315f21feab8d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weaver-0.1.0-sources.jar",
          "url": "weaver-0.1.0-sources.jar",
          "size": 6396,
          "sha512": "b096896bfc38ec29220bb7ff6a30feb8d97fe61696a2637069e505be63490fbeb09897b2010edbc189eef355acd290368b4e520ab364feb6f9e57ba66af8aaa7",
          "sha256": "6a1995759eac95042fa1e5745e8d255b151a6e12e166bd6080b7e9d2358b5a96",
          "sha1": "2b8c4906462311ff638b7bcd562f162460e8106e",
          "md5": "6e8725823a38be9f6316cf30ff37d40c"
        }
      ]
    }
  ]
}
