{
  "formatVersion": "1.1",
  "component": {
    "group": "net.turtton",
    "module": "weaver",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "weaver-0.1.3.jar",
          "url": "weaver-0.1.3.jar",
          "size": 15352,
          "sha512": "4e867b726f9455698d1e7dd30061bfbe831fed7f3cb9c61a122a308d5c392b6c7ede317b5d4546cb75ffc9bd50c9104a3c5549785951fde3b036d8c36df8119e",
          "sha256": "19ad9b9b3227a57e1391e1a8c6082bd62149742cf79f2793e1877bdd15fa8b8d",
          "sha1": "97c27c0072b188fe11e4c4a7191b845cc8923d74",
          "md5": "b2f8820b5334fe32a62123ca24aac253"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.7.1+kotlin.1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "weaver-0.1.3.jar",
          "url": "weaver-0.1.3.jar",
          "size": 15352,
          "sha512": "4e867b726f9455698d1e7dd30061bfbe831fed7f3cb9c61a122a308d5c392b6c7ede317b5d4546cb75ffc9bd50c9104a3c5549785951fde3b036d8c36df8119e",
          "sha256": "19ad9b9b3227a57e1391e1a8c6082bd62149742cf79f2793e1877bdd15fa8b8d",
          "sha1": "97c27c0072b188fe11e4c4a7191b845cc8923d74",
          "md5": "b2f8820b5334fe32a62123ca24aac253"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weaver-0.1.3-sources.jar",
          "url": "weaver-0.1.3-sources.jar",
          "size": 6439,
          "sha512": "e19667bddf9b418ac6751e4cec483ae7590d67187c18a7f674cdfbec39261d11907ab30fa865347066a8e9ea6ffa2aa6ed591060f92b2b72e5581a9fe02d94c0",
          "sha256": "c67317b789298b39b327e65acb925491ce728fa96eea7e57b38ddd682b68ac78",
          "sha1": "50cc4ea303590f0e437d123b32e1a4435408437c",
          "md5": "f83183a9cd91e0e8f0894a7adc4dfa9d"
        }
      ]
    }
  ]
}
