{
  "formatVersion": "1.1",
  "component": {
    "group": "net.turtton",
    "module": "weaver",
    "version": "1.19.1+build.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "weaver-1.19.1+build.3.jar",
          "url": "weaver-1.19.1+build.3.jar",
          "size": 16204,
          "sha512": "7ab72d7911960880b71a9d0a4db69f6d60ecdc64f66407868e3f510528754d46ce0ae2f4ce2af8ca4939b64c142093598c8e732054b379e04e3f3af56a857328",
          "sha256": "d86266173a6b1ab95d51bab9e5445e165a96833b6ef65e4b9194d7f9db6e9fbb",
          "sha1": "4c9ecbdc6cf2260a75a0219f70e55302c91dd3be",
          "md5": "6a551b3754f7763e8a4a9daaa9b1d286"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.5+1.19.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.2+kotlin.1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "weaver-1.19.1+build.3.jar",
          "url": "weaver-1.19.1+build.3.jar",
          "size": 16204,
          "sha512": "7ab72d7911960880b71a9d0a4db69f6d60ecdc64f66407868e3f510528754d46ce0ae2f4ce2af8ca4939b64c142093598c8e732054b379e04e3f3af56a857328",
          "sha256": "d86266173a6b1ab95d51bab9e5445e165a96833b6ef65e4b9194d7f9db6e9fbb",
          "sha1": "4c9ecbdc6cf2260a75a0219f70e55302c91dd3be",
          "md5": "6a551b3754f7763e8a4a9daaa9b1d286"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weaver-1.19.1+build.3-sources.jar",
          "url": "weaver-1.19.1+build.3-sources.jar",
          "size": 6443,
          "sha512": "c022c2508e6218d5bc920903e62f178bbd7d101cb76b2406a387f292efaf73d815356cd7f5ff9381d463ddd2f0aea99777a183da0eaf373806f6a8e4dbd90330",
          "sha256": "3b429c93653d88aebe4a186c27039efe249d9805fc21f8c61dbcbe692739d11d",
          "sha1": "ce3d16f7a4ea882dddbcf89d5426c95d6a1519c6",
          "md5": "4cf0d605d5c5f632ff75bdc152762435"
        }
      ]
    }
  ]
}
