{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-react-test/19.0.0-2025.2.8+build.8/kotlin-react-test-19.0.0-2025.2.8+build.8.module",
    "group": "net.cyberflame.kotlin-react-test",
    "module": "kotlin-react-test",
    "version": "19.0.0-2025.2.8+build.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.8.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.8.klib",
          "size": 526,
          "sha512": "2396bdabdaeb7bc97adf504c1267d697d2640a5bc426c87d4f32c9bfcaf36ac6e00b9c632e566cda9812352e8c34d9b451150f0a7ae02c331a45774d18df4d4c",
          "sha256": "94211170e19aa9d4dcb5c2f721020356415177fa6366bcb9562900eb17c3c05c",
          "sha1": "ffc45fae77279eb1ceb674319a0b6b006ed503be",
          "md5": "449848e046a2074c50616b1687fada86"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.8.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.8.klib",
          "size": 526,
          "sha512": "2396bdabdaeb7bc97adf504c1267d697d2640a5bc426c87d4f32c9bfcaf36ac6e00b9c632e566cda9812352e8c34d9b451150f0a7ae02c331a45774d18df4d4c",
          "sha256": "94211170e19aa9d4dcb5c2f721020356415177fa6366bcb9562900eb17c3c05c",
          "sha1": "ffc45fae77279eb1ceb674319a0b6b006ed503be",
          "md5": "449848e046a2074c50616b1687fada86"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.8-sources.jar",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.8-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
