{
  "formatVersion": "1.1",
  "component": {
    "group": "net.turtton",
    "module": "weaver",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "weaver-0.1.4.jar",
          "url": "weaver-0.1.4.jar",
          "size": 16525,
          "sha512": "beaba7f3aaacaffcc814d36ce58c633873a243651ca27f9078a1ec6b0cc11dc84e0e27b532634121fc93c1018d505f8b8fc143b9b790bc9d6b9cf1217f419cd0",
          "sha256": "4e6a32baaab4b79744c59e591e1441bdba40a042f0e86f9984f2b0467ed6a820",
          "sha1": "3552628d539c1296f4ea86c28568d22085b1fcff",
          "md5": "be5b3e56489f8998be4c71ef666dbc13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.7.1+kotlin.1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "weaver-0.1.4.jar",
          "url": "weaver-0.1.4.jar",
          "size": 16525,
          "sha512": "beaba7f3aaacaffcc814d36ce58c633873a243651ca27f9078a1ec6b0cc11dc84e0e27b532634121fc93c1018d505f8b8fc143b9b790bc9d6b9cf1217f419cd0",
          "sha256": "4e6a32baaab4b79744c59e591e1441bdba40a042f0e86f9984f2b0467ed6a820",
          "sha1": "3552628d539c1296f4ea86c28568d22085b1fcff",
          "md5": "be5b3e56489f8998be4c71ef666dbc13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weaver-0.1.4-sources.jar",
          "url": "weaver-0.1.4-sources.jar",
          "size": 6616,
          "sha512": "6e08c11b0b3a8f3e1249714cbbeda25bf5dd78e8b882d06cb393a164c5dc39d9178191baa522d19521b6b9c4c89297ca53ef50a6c618b4db074e222a68601bb0",
          "sha256": "798e50794c250bb8758c244c6af06d07b07b57882fc1607daa1626dfebd1f8c6",
          "sha1": "dd5515d602248d3c9c9d54097b09e84055ae0791",
          "md5": "072682058e0177146024d5d14b6f63c7"
        }
      ]
    }
  ]
}
