{
  "formatVersion": "1.1",
  "component": {
    "group": "net.turtton",
    "module": "weaver",
    "version": "1.19+build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "weaver-1.19+build.1.jar",
          "url": "weaver-1.19+build.1.jar",
          "size": 15799,
          "sha512": "2f5b085bcdd24a56a8376fd58cca4a81468afbb7229c9af18aa067ac2019bf566d24f5b8d3f3f9e04a1bc842e174594214ffd0e0ad3aa6745952a8d00847c1c4",
          "sha256": "0e5b987e529d5a6e308767f30a25ddb2ce3ee46a1415c1db375289648f8e1267",
          "sha1": "fbe090c42b4d7aca40657ac8283e30c3510da44c",
          "md5": "348c53d0e95f0e2dfdc745242c9dbfcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.2+kotlin.1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "weaver-1.19+build.1.jar",
          "url": "weaver-1.19+build.1.jar",
          "size": 15799,
          "sha512": "2f5b085bcdd24a56a8376fd58cca4a81468afbb7229c9af18aa067ac2019bf566d24f5b8d3f3f9e04a1bc842e174594214ffd0e0ad3aa6745952a8d00847c1c4",
          "sha256": "0e5b987e529d5a6e308767f30a25ddb2ce3ee46a1415c1db375289648f8e1267",
          "sha1": "fbe090c42b4d7aca40657ac8283e30c3510da44c",
          "md5": "348c53d0e95f0e2dfdc745242c9dbfcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "weaver-1.19+build.1-sources.jar",
          "url": "weaver-1.19+build.1-sources.jar",
          "size": 6349,
          "sha512": "9c63d6d2adc8f263df9895b3645bfada975625ca15687b3dc979b64ff94fdc11d1da9109b8ae73960999b26247e6028983384913679c8d2c3d2cfc15774bd6c5",
          "sha256": "7e5e8b248e6622fef5cfc60d952625cdf1b068f59482525b46d22a40e36ab56d",
          "sha1": "84606e19a0e6f92e85df64e0cab8731949f21a3d",
          "md5": "bf6290a17eae758e344d421897a2ca91"
        }
      ]
    }
  ]
}
