{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-react-test/19.0.0-2025.2.8+build.11/kotlin-react-test-19.0.0-2025.2.8+build.11.module",
    "group": "net.cyberflame",
    "module": "kotlin-react-test",
    "version": "19.0.0-2025.2.8+build.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.11.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.11.klib",
          "size": 527,
          "sha512": "ad73bf7e0d20fc0f40fa36e34f27124ecbaee971adaee08832e309d86226dfdf5971e1c6530b0f3cef473797ee2893af5f4b21826b024941c427eaef6a230d0f",
          "sha256": "9a03003965761abc2759a30049c5e80a45eebcec60c03f17094103b252994d4c",
          "sha1": "803c060375807bb00e5953464f011e625759aa91",
          "md5": "f8785a81efec0783cd8d8c752a531af9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.11.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.11.klib",
          "size": 527,
          "sha512": "ad73bf7e0d20fc0f40fa36e34f27124ecbaee971adaee08832e309d86226dfdf5971e1c6530b0f3cef473797ee2893af5f4b21826b024941c427eaef6a230d0f",
          "sha256": "9a03003965761abc2759a30049c5e80a45eebcec60c03f17094103b252994d4c",
          "sha1": "803c060375807bb00e5953464f011e625759aa91",
          "md5": "f8785a81efec0783cd8d8c752a531af9"
        }
      ]
    }
  ]
}
