{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-react-test/19.0.0-2025.2.8+build.7/kotlin-react-test-19.0.0-2025.2.8+build.7.module",
    "group": "net.cyberflame.kotlin-react-test",
    "module": "kotlin-react-test",
    "version": "19.0.0-2025.2.8+build.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.7.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.7.klib",
          "size": 526,
          "sha512": "823e862643ff971f4a6b89b0530e727c720571b08251f512d1b823ee64d2e610077b53e365162ac5dd4598e43730b580edfbbab452b4b2042cbda6c301c2417d",
          "sha256": "9d453bffb8478fd5c10880b061701f080f122987225399137626f81191f59b0b",
          "sha1": "942f9e01a8bd0ef2e1d023330ba332034bf81300",
          "md5": "5c4162285eb01dbc267eda32758cf0cc"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "2025.2.8-19.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.7.klib",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.7.klib",
          "size": 526,
          "sha512": "823e862643ff971f4a6b89b0530e727c720571b08251f512d1b823ee64d2e610077b53e365162ac5dd4598e43730b580edfbbab452b4b2042cbda6c301c2417d",
          "sha256": "9d453bffb8478fd5c10880b061701f080f122987225399137626f81191f59b0b",
          "sha1": "942f9e01a8bd0ef2e1d023330ba332034bf81300",
          "md5": "5c4162285eb01dbc267eda32758cf0cc"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-react-test-js-19.0.0-2025.2.8+build.7-sources.jar",
          "url": "kotlin-react-test-js-19.0.0-2025.2.8+build.7-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
